name: Build and Deploy to Main Repo

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print Repository Variable
        run: |
          echo "Pushing to : ${{ vars.PROD_USER }}/${{ vars.PROD_REPO }}"

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Build Gatsby Site
        run: npm run build

      - name: Push build to main repo
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git clone --quiet https://${{ github.actor }}:${{ secrets.PROD_ACCESS_TOKEN }}@github.com/$PROD_USER/$PROD_REPO.git
          cp -rf public/* $PROD_REPO/
          cd $PROD_REPO
          git add .
          git commit -m "Update puzzles component"
          git push
        env:
          PROD_REPO: ${{ vars.PROD_REPO }}
          PROD_USER: ${{ vars.PROD_USER }}
