name: Build and Deploy to Main Repo

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Build Gatsby Site
        run: npm run build

      - name: Push build to main repo
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.PROD_USER }}/${{ env.PROD_REPO }}.git
          cp -r public/* ${{ env.PROD_REPO }}
          cd ${{ env.PROD_REPO }}
          git add .
          git commit -m "Update puzzles component"
          git push
